#!/bin/bash

# First, let's see the amount of disk usage / free

echo "Disk Free"
df -H

echo -e "Disk Usage\n"
echo "What size are you looking for?"
echo -e "\t> Kilobyte (K)?"
echo -e "\t> Megabyte (M)?"
echo -e "\t> Gigabyte (G)?"
echo -e "\t> ALL (hit enter)"
read ans

runCommand(){
	# echo "Run Command"
	if [ $1 ];
		then sudo du -d 1 -h | grep '.[0-9]'$1 | sort -n -k 1
	else 
		sudo du -d 1 -h
	fi;
}

showDiskUsage () {
	case $1 in 
		"K" | "k" | "Kilobyte" | "kilobyte")
			runCommand 'K'
		;;
		"M" | "m" | "Megabyte" | "megabyte")
			runCommand 'M'
		;;
		"G" | "g" | "Gigabyte" | "gigabyte")
			runCommand 'G'
		;;
		*)
			runCommand
	esac;
}

if [ $ans ];
	then
	echo -e "\n\t...Searching...\n"
	showDiskUsage $ans;
else
	runCommand
fi;

